[#status]
image:https://img.shields.io/badge/License-LGPL%20v3-blue.svg[link="https://www.gnu.org/licenses/lgpl-3.0"]
image:https://maven-badges.herokuapp.com/maven-central/com.github.funthomas424242/mypocketmod/badge.svg?style=flat["Maven Central", link="https://maven-badges.herokuapp.com/maven-central/com.github.funthomas424242/mypocketmod"]
image:https://api.bintray.com/packages/funthomas424242/funthomas424242-libs/mypocketmod/images/download.svg[link="https://bintray.com/funthomas424242/funthomas424242-libs/mypocketmod/_latestVersion"]
image:https://travis-ci.org/FunThomas424242/mypocketmod.svg?branch=master["Build Status", link="https://travis-ci.org/FunThomas424242/mypocketmod"]
image:https://api.codacy.com/project/badge/Grade/88bf76546176437ea389629a2087d1b5["Codacy code quality", link="https://www.codacy.com/app/FunThomas424242/mypocketmod?utm_source=github.com&utm_medium=referral&utm_content=FunThomas424242/mypocketmod&utm_campaign=Badge_Grade"]
image:https://codecov.io/gh/FunThomas424242/mypocketmod/branch/master/graph/badge.svg[link="https://codecov.io/gh/FunThomas424242/mypocketmod"]
image:http://images.webestools.com/buttons.php?frm=2&btn_type=11&txt=Scrum Board["Scrum Board,scaledwidth="15%"", link="https://github.com/FunThomas424242/mypocketmod/projects/1"]

image:https://img.shields.io/badge/readme%20style-standard-brightgreen.svg?style=flat-square["standard-readme compilant",link="https://github.com/RichardLitt/standard-readme"]

== MyPocketmod
Kommandozeilenprogramm welches 8 PDF Dokumente in eine PDF Seite konvertiert, die im http://pocketmod.com[Pocketmod Style] gefaltet werden kann.

== Inhaltsverzeichnis

- link:#hintergrund[Hintergrund]
- link:#installation[Installation]
- link:#nutzung[Nutzung]
- link:#literatur[Literatur und Quellen]
- link:#projektverantwortlicher[Projektverantwortlicher]
- link:#unterstützung[Unterstützung]
- link:#lizenz[Lizenz]

[#hintergrund]
== Hintergrund
Ich mag es, mein Leben im GTD Style zu organisieren und mag daher auch pocketmod.com. Die Nutzung hatte aber für mich 2 große Einschränkungen:

1. Das Offline Werkzeug ist nur für Windows verfügbar und ich besitze keinen Windows Rechner privat.
2. Das Online Werkzeug bietet nur eine feste Anzahl an Vorlagen und lässt sich somit nicht flexibel genug personalisieren.

Diese Einschränkungen möchte ich beseitigen, indem ich das Werkzeug MyPocketmod zur Verfügung stelle, welches auf Java basiert und damit bei guter Programmierung
plattformübergreifend arbeiten sollte (Hier habe ich großen Lernbedarf und bin auf Feedback der Nutzer angewiesen, da ich nur temporär Zugang zu einem
Windows PC besitze - er dient sonst als Spiele PC und möchte nicht mit Entwicklerwerkzeugen verunreinigt werden).
Bei der Nutzung von MyPocketmod soll der Nutzer selbst konfigurieren können welche PDF Dokumente (immer die erste Seite wird genutzt) zu einer PDF Seite
zusammengefügt werden. Die Ausrichtung der Seiten auf der finalen Seite soll auch konfigurierbar sein.

[#installation]
== Installation

Harte und rauhe Methode, welche aber immer gehen sollte

1. Ein "Projektverzeichnis" anlegen.
2. Prüfen, dass Java installiert ist (JRE muss ausreichen).
3. Das MyPocketmod JAR Archiv welches auch alle Abhängigkeiten enthält herunterladen und im "Projekverzeichnis" ablegen


[#nutzung]
== Nutzung

1. Konsole öffnen und ins "Projektverzeichnis" wechseln.
2. Im Projektverzeichnis 8 PDF Dokumente ablegen, welche bitte `Seite1.pdf`, `Seite2.pdf` bis `Seite8.pdf` benannt sind.
3. Auf der Kommandozeile `java -jar <pfad zum JAR Archiv>` eingeben und mit Enter zur Ausführung bringen -> Es entsteht eine Konfigurationsdatei und eine PDF Datei welche das final Pocketmod enthält.

[#literatur]
== Literatur und Quellen im Netz

* http://pocketmod.com
* http://www.alexander-merz.com/42.html
* https://riptutorial.com/Download/jasper-reports-de.pdf
* https://community.jaspersoft.com/documentation/tibco-jaspersoft-studio-user-guide/v630/getting-started-jaspersoft-studio
* https://github.com/noffle/art-of-readme[Art of Readme] - Erlerne die Kunst gute READMEs zu schreiben.
* https://github.com/davidbgk/open-source-template/[open-source-template] - A README template to encourage open-source contributions.
* https://www.makeareadme.com/
* https://github.com/RichardLitt/standard-readme
* https://github.com/RichardLitt/generator-standard-readme/
* https://github.com/noffle/art-of-readme
* https://keepachangelog.com/de
* http://boeffi.net/tutorials/local-mock-variables-ein-dritter-weg-in-jmockit/

[#projektverantwortlicher]
== Projektverantwortlicher

https://github.com/FunThomas424242[@Huluvu424242 (alias FunThomas424242)]

[#unterstützung]
== Unterstützung

Unterstützung ist jederzeit erwünscht. Ein gelungener Einstieg sollte sich über Duchlesen, Prüfen/Testen, Korrigieren/Weiterentwickeln
und Änderungen als Pull-Request einstellen, ergeben. Du kannst aber auch jederzeit gern ein Ticket öffnen
unter: https://github.com/funthomas424242/mypocketmod/issues/new/choose[Ticket Erstellen].

Dieses Projekt folgt den unter https://funthomas424242.github.io/mypocketmod/code-of-conduct.txt[Verhaltenskodex] abgelegten Verhaltensregeln.
Welche auch unter https://www.contributor-covenant.org/de/version/1/4/code-of-conduct/[Verhaltenskodex für Unterstützer] veröffentlicht wurden.

=== Unterstützer

Dieses Projekt lebt vom Support all seiner Unterstützer genau wie auch vom Support all jener welche nicht namentlich bekannt sind aber
das Projekt im Internet bekannt machen oder anderweitig unterstützen.

Vielen Dank für all Euren Suppprt!

////
Ab 100 Sterne auf github ist eine Verwaltung über opencollective für OpenSource Projekte möglich
This project exists thanks to all the people who contribute.
<a href="graphs/contributors"><img src="https://opencollective.com/standard-readme/contributors.svg?width=890&button=false" /></a>
////

[#lizenz]
== Lizenz

link:LICENSE[LGPL-3.0] © link:https://github.com/FunThomas424242[Huluvu424242 (alias FunThomas424242)]

